### ISSUE TITLE
another DBus exception error.

### ISSUE THREAD

**Issue by LittleCannon** [Baldomo/asusctltray#12]
Hi, I saw that you add support for newest supegfxctl, but upon installlation when I run program I got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/asusctltray", line 335, in <module>
    TrayIcon()
  File "/usr/local/bin/asusctltray", line 109, in __init__
    self.build_menu()
  File "/usr/local/bin/asusctltray", line 118, in build_menu
    self.add_graphics("Graphics")
  File "/usr/local/bin/asusctltray", line 174, in add_graphics
    current_graphics = self.get_current_graphics()
  File "/usr/local/bin/asusctltray", line 194, in get_current_graphics
    mode = self.gfx_proxy.Mode()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method 'Mode'
```

Did I miss something again?

Environment:
OS: Debian GNU/Linux bookworm/sid x86_64 
Host: ROG Zephyrus G14 GA401QM_GA401QM 1.0 
Kernel: 5.15.0-3-amd64 
DE: Plasma 5.23.5 
WM: KWin

**Comment by Baldomo** [comment]
Would you mind sending the output of `supergfxctl --version`?

**Comment by LittleCannon** [comment]
Supegfxctl does not return anything (there is no version switch)

Asusctl -v returns:

```
App and daemon versions:
      asusctl v4.0.6
        asusd v4.0.6

Component crate versions:
    rog-anime v1.3.0
     rog-aura v1.1.0
     rog-dbus v4.0.2
 rog-profiles v1.1.3
rog-supported v4.0.0

Product family: ROG Zephyrus G14
Board name: GA401QM
```

**Comment by Baldomo** [comment]
Sounds like you have a very outdated version of `supergfxctl`. The `--version` arg used to work in 3.x too. Since the dbus API was changed rather drastically in v3 - v4 the script doesn't work until you update `supergfxctl`. And, as a side note, Debian-based distros aren't officially supported by `asusctl` and the like, so you'll probably have to do some testing and fix stuff yourself.

**Comment by LittleCannon** [comment]
Following your advice, I recompiled again asusctl. and it bumped it to version 4.0.7, but then I remembered that supergfxctl is separate project and you were right, I had really old version. 
Somehow I thought/remembered that supergfxctl is part of asusctl (don't ask me why.)


Anyway, with new supergxctl everything works.

Again, thank you on really quick answers.
