### ISSUE TITLE
Installing from AUR

### ISSUE THREAD

**Issue by m0nk3h** [Baldomo/asusctltray#13]
I previously installed this with the install.sh, but when installing via the new AUR method, I get the following error. (Supergfxctl & asusctl are both installed.)

error: failed to commit transaction (conflicting files)
supergfxctl: /usr/bin/supergfxctl exists in filesystem
supergfxctl: /usr/bin/supergfxd exists in filesystem
supergfxctl: /usr/lib/systemd/system-preset/supergfxd.preset exists in filesystem
supergfxctl: /usr/lib/systemd/system/supergfxd.service exists in filesystem
supergfxctl: /usr/lib/udev/rules.d/90-supergfxd-nvidia-pm.rules exists in filesystem
supergfxctl: /usr/share/X11/xorg.conf.d/90-nvidia-screen-G05.conf exists in filesystem
supergfxctl: /usr/share/dbus-1/system.d/org.supergfxctl.Daemon.conf exists in filesystem
Errors occurred, no packages were upgraded.

Arch (Garuda Barebones), Asus ROG Flow X13

**Comment by Baldomo** [comment]
You need to remove these files before installing with the AUR, as pacman will complain when files are already present and not tracked as a package:

```
/usr/local/bin/asusctltray
/usr/share/applications/asusctltray.desktop
/usr/share/pixmaps/asusctltray.svg
```

I can also see you have a problem with your supergfxd installation, did yuu install it from source?

**Comment by m0nk3h** [comment]
Oh, thank you. I didn't realise there were some uninstall steps between switching installation methods.  As for supergfxctl, I did install it manually from source as I was checking an unreleased version for Fluke.  I'll delete the above files, reinstall supergfxctl from the g14 repo, and switch to the AUR method. Thanks for your help, and for asusctltray. :)

**Comment by Baldomo** [comment]
No problem. Thank you for opening this issue, so anyone who'll look for a similar issue may find a solution here. For the time being, I'm closing this.
