### ISSUE TITLE
Boost control

### ISSUE THREAD

**Issue by AFAgarap** [Baldomo/asusctltray#17]
Hello! So, with `sway` + `waybar` running on Wayland as per this issue #16 , I got the missing tray icon rendered correctly. Not sure what did that.

However, when I tried enabling/disabling the CPU frequency boost, nothing happens. Upon checking `journalctl -f`, I got the following error,

```
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]: Traceback (most recent call last):
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:   File "/usr/lib64/python3.10/codecs.py", line 310, in __init__
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:     IncrementalDecoder.__init__(self, errors)
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]: RecursionError: maximum recursion depth exceeded
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]: During handling of the above exception, another exception occurred:
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]: Traceback (most recent call last):
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:   File "/usr/local/bin/asusctltray", line 85, in inner
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:     callback(self, widget)
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:   File "/usr/local/bin/asusctltray", line 373, in _disable_boost
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:     if not self._is_boost_enabled():
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:   File "/usr/local/bin/asusctltray", line 357, in _is_boost_enabled
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]:     data = open(self.boost_ctrl["path"], "r").read()[:-1]
Jul 16 06:19:55 rogStrixG15 /usr/libexec/gdm-wayland-session[53233]: RecursionError: maximum recursion depth exceeded while calling a Python object
```

May I know what should be done to fix this? Your help would be greatly appreciated, and thanks again for developing `asusctltray`.

**Comment by AFAgarap** [comment]
If ever anyone encounters this same issue, I was able to resolve this by installing `lxpolkit`,

```
$ sudo dnf install lxpolkit
$ whereis lxpolkit
/usr/bin/lxpolkit
```

Then, I let sway execute it (set in `~/.config/sway/config`),

```
exec /usr/bin/lxpolkit
```

Now, I can switch between CPU frequency boost enabled/disabled.

**Comment by Baldomo** [comment]
I was just about to try and troubleshoot this, nice job! Actually, I should add a check for `pkexec` being installed, because it's technically not a hard dependency. Thanks!

**Comment by AFAgarap** [comment]
Thanks too! Actually, my config was missing a policy kit authenticator when I moved from GNOME to SwayWM + Waybar for Fedora 36. I'm still setting up my machine, which I purchased 2 weeks ago. Right now though, I'm almost done setting it up. Just cosmetics left for Waybar.
