### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by LittleCannon** [Baldomo/asusctltray#2]
It is not really an issue, but more as an idea.

Is it possible to have 3 different color coded tray icons (green, yellow and red, same as asus-notify daemon has) that would change depending which profile is active?

**Comment by Baldomo** [comment]
While it could certainly be done, I'd rather keep the functionality as is. I made this script to be as simple as possible and I would personally not use this feature as I prefer the menu the way it is. Adding configuration to toggle settings would require way more code, not to mention the extra icon colors/images (the current one is fully self-contained encoded in base64). I also thought about usability and checking which profile is active only takes one click, so it's fairly ok as is. Moreover, many people use slim panels/tray bars so the icon (which is already way too detailed to have good recognizability on HiDPI) would become illegible when colored. If this project needs more complexity in the future (such as a GUI or amore windows etc) I'll gladly implement colored icons but for now I feel like it's unneeded. Thank you for the suggestion, though! Issues like these are welcome here.
