### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by sobornostea** [Baldomo/asusctltray#4]
I am currently writing a PKGBUILD for this program, is there any licensing information ?

**Comment by Baldomo** [comment]
Sorry for the late response. No, `asusctltray` doesn't have a license, but I was planning on adding one (MIT) so I might as well just add it now. Thank you for the PKGBUILD! Having stuff on the AUR is always useful, I'll link the package in the README as soon as it's ready if you don't mind.
