### ISSUE TITLE
Support for supergfxctl v3.x.x

### ISSUE THREAD

**Issue by ShadyF** [Baldomo/asusctltray#9]
`supergfxctl` just released v3.0.0 (https://gitlab.com/asus-linux/supergfxctl/-/releases/3.0.0) in which the graphics modes have been renamed. This causes `asusctltray` to display different graphics mode than that which is set by `supergfxctl`

For example, setting the graphics mode to `integrated` via `supergfxctl` results in `compute` being the graphics mode selected in `asusctltray` on my G14.

I'm guessing the graphics mode indices and their respective display names have to be updated?

Thanks!

**Comment by Baldomo** [comment]
Thank you for the bug report, fixed!

**Comment by ShadyF** [comment]
Thank you so much for the quick fix! Much appreciated.
